# Generated by Django 3.1.7 on 2021-03-04 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('snack_name', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('purchaser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snacks.snacks')),
            ],
        ),
    ]
