# Generated by Django 3.1.7 on 2021-03-04 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snacks',
            name='snack_name',
            field=models.CharField(help_text='Enter a SNACK!', max_length=64),
        ),
    ]
